### ISSUE TITLE
Support for `du` or `ls -al`

### ISSUE THREAD

**Issue by nottombrown** [hauntsaninja/boostedblob#1]
I'd love to be able to use boostedblob to check how much data is in a directory

**Comment by hauntsaninja** [comment]
`bbb ls -l` already works, and `bbb lstree -l` / `bbb lsr -l` is similar to du.

**Comment by hauntsaninja** [comment]
`bbb lstree -l` will now show a summary with total size. `bbb du` / `bbb llr` / `bbb lsr -l` are other ways to spell the same command. Thanks to @8enmann !
